### ISSUE TITLE
Request - Debugger Support with Vice

### ISSUE THREAD

**Issue by paulhocker** [tomconte/vscode-kickassembler#2]
Debugger support would be a great addition to the editor.

**Comment by paulhocker** [comment]
I think this might be easier if it simply provided a way to open the compiled program with the excellent C64Debugger app:

https://sourceforge.net/projects/c64-debugger/

**Comment by tomconte** [comment]
Thanks for your suggestion! I belatedly implemented this in 9924f66359a12ebb43e5736f252fc33d301d6fdc.
